version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/storage:/data
    command: redis-server --appendonly yes
  bjs-server:
    build: ./server
    depends_on:
      - redis
    ports:
      - 8080:8080
  bjs-client:
    build: ./client/
    depends_on:
      - bjs-server
    ports:
      - 80:80
