version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  # lb:
  #   image: 'dockercloud/haproxy:latest'
  #   links:
  #     - server
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ~/.ssl:/certs/
  #   environment:
  #     - CA_CERT_FILE:/certs/cert.pem
