version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/storage:/data
    command: redis-server --appendonly yes
  bjs-server:
    image: seedow/bjs-server:p-incr
    # build: ./server
    depends_on:
      - redis
    ports:
      - 8080:8080
  bjs-client:
    image: seedow/bjs-client:p
    # build: ./client
    depends_on:
      - bjs-server
    ports:
      - 8081:80
    environment:
      # SERVER: 52.28.182.213
      SERVER: $BJS_SERVER_HOST
    restart: always
    command: sh -c "sed -i -e 's/$$SERVER/'"$$SERVER"'/g' src/js/main.js; nginx -g 'daemon off;'"
  bjs-client-worker:
    image: seedow/bjs-client-worker:p
    depends_on:
      - bjs-server
    ports:
      - 80:80
    environment:
      # SERVER: 52.28.182.213
      SERVER: $BJS_SERVER_HOST
    restart: always
    command: sh -c "sed -i -e 's/$$SERVER/'"$$SERVER"'/g' src/js/main.js; nginx -g 'daemon off;'"
