version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./db/storage:/data
    command: redis-server --appendonly yes
  bjs-server:
    builds: ./server
    depends_on:
      - redis
    ports:
      - 8080:8080
  bjs-client:
    builds: ./client
    depends_on:
      - bjs-server
    ports:
      - 80:80
    environment:
      # SERVER: 52.28.182.213
      SERVER: $BJS_SERVER_HOST
    restart: always
    command: sh -c "sed -i -e 's/$$SERVER/'"$$SERVER"'/g' index.html; nginx -g 'daemon off;'"
